apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: octopub-production
  namespace: argocd
  annotations:
   argo.octopus.com/project: "octopub"
   argo.octopus.com/environment: "production"
spec:
  project: default
  source:
    repoURL: https://github.com/octopussolutionsengineering/Itau-octopub.git
    targetRevision: HEAD
    path: manifests/production
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
    - CreateNamespace=true